Repository pabfrasan/decide, pull requests merged in 2021-01, with the labels that each got.

#132 Develop authentication pabmordel
  .gitignore
  .vscode/settings.json
  decide/authentication/forms.py
  decide/authentication/templates/edit_user_profile.html
  decide/authentication/templates/user_profile.html
  decide/authentication/urls.py
  decide/authentication/views.py
Labels: autenticacion, enhancement

#172 Fix de Editar Usuario
  decide/authentication/templates/edit_user_profile.html
  decide/authentication/templates/user_profile.html
  decide/authentication/views.py
Labels: autenticacion, enhancement

#189 Develop visualizer gabriel a developVisualizer
  decide/visualizer/templates/visualizer/visualizer_home.html
  decide/visualizer/views.py
Labels: Visualizer, enhancement

#190 Tests Editar Perfil
  decide/authentication/tests.py
  decide/authentication/views.py
Labels: autenticacion

#201 Tests restantes de editar perfil pabmordel
  decide/authentication/tests.py
Labels: autenticacion, enhancement

#205 Gráfica en tiempo real visualizer.html
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/views.py
Labels: Visualizer, enhancement

#210 Actualizacion de rama general
  decide/voting/tests.py
Labels: Votacion, enhancement

#226 Develop visualizer gabriel Test graficas
  decide/visualizer/tests.py
Labels: Visualizer

#237 Develop authentication pabmordel
  decide/authentication/forms.py
  decide/authentication/templates/edit_user_profile.html
  decide/authentication/tests.py
  decide/authentication/views.py
Labels: autenticacion, bug
